# Version docker-compose
version: '3.7'

# Servicios
services:

  wildfly:
    build: /wildfly
    container_name: wildfly-server
    ports:
      - 8080:8080 
      - 9990:9990 
      - 8009:8009
    depends_on:
      - db
    volumes:
      - v-wildfly:/opt/jboss/wildfly/standalone/deployments/

  # Servicio MySQL
  db:
    build: /mysql
    container_name: bbdd
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - v-mysql:/var/lib/mysql

# Volumenes
volumes:
  v-wildfly:
  v-mysql: