# La versión 3 es la más utilizada y la que se recomienda
version: '3'

# Configuración de los servidores que vamos a necesitar
services: 
 
  # db es el nombre que vamos a dar a este primer servidor
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  db:
    image: mysql:5.7
    container_name: servidor_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: iban
      MYSQL_PASSWORD: ibansola1!
      MYSQL_DATABASE: pruebas
    volumes:
      - data:/var/lib/mysql

  apache:
    build: apache/
    container_name: servidor_web
    ports:
      - 80:80
    volumes:
      - proyecto:/var/www/html/

  php:
    build: php/
    container_name: servidor_php
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/

  phpmyadmin:
    build: phpmyadmin/
    container_name: servidor_phpadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    volumes:
      - proyecto:/usr/share/phpmyadmin
    depends_on:
      - db  

volumes: 
 proyecto:
 data: 