# Version docker-compose
version: '3.7'

# Servicios
services:

  www:
      build: apache/
      container_name: apache
      ports:
        - 80:80
      volumes:
        - proyecto:/var/www/html/
        - github:/proyecto-birt/mysql

  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - github:/docker-entrypoint-initdb.d/
      - datosBBDD:/var/lib/mysql

  php:
    build: php/
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_HOST=mysql
    volumes:
      - proyecto:/usr/share/phpmyadmin
    depends_on:
      - mysql 

volumes:
  proyecto:
  datosBBDD:
  github: